// Project 8.3: Resource-Shared Scheduled SC Decoder N=16
//
// Auto-generated by scripts/generate_sc_decoder_n16_shared_rtl.py
//
// Conventions:
//   frozen_mask[i] = 1 -> frozen bit, force u_i = 0
//   frozen_mask[i] = 0 -> information bit
//   hard decision: LLR < 0 -> 1, otherwise 0
//   g(a,b,u): b + a if u=0, b - a if u=1
//   u_hat[0] = u0, LSB-first ordering

`timescale 1ns/1ps

module sc_decoder_n16_shared #(
    parameter W_IN  = 6,
    parameter W_INT = 10
)(
    input  wire clk,
    input  wire rst_n,
    input  wire start,

    input  wire signed [W_IN-1:0] llr0,
    input  wire signed [W_IN-1:0] llr1,
    input  wire signed [W_IN-1:0] llr2,
    input  wire signed [W_IN-1:0] llr3,
    input  wire signed [W_IN-1:0] llr4,
    input  wire signed [W_IN-1:0] llr5,
    input  wire signed [W_IN-1:0] llr6,
    input  wire signed [W_IN-1:0] llr7,
    input  wire signed [W_IN-1:0] llr8,
    input  wire signed [W_IN-1:0] llr9,
    input  wire signed [W_IN-1:0] llr10,
    input  wire signed [W_IN-1:0] llr11,
    input  wire signed [W_IN-1:0] llr12,
    input  wire signed [W_IN-1:0] llr13,
    input  wire signed [W_IN-1:0] llr14,
    input  wire signed [W_IN-1:0] llr15,

    input  wire [15:0] frozen_mask,

    output reg  [15:0] u_hat,
    output reg         busy,
    output reg         done
);

    localparam integer STATE_W = 7;

    localparam [STATE_W-1:0] S_IDLE = 0;
    localparam [STATE_W-1:0] S_LOAD = 1;
    localparam [STATE_W-1:0] S_OP_000 = 2;
    localparam [STATE_W-1:0] S_OP_001 = 3;
    localparam [STATE_W-1:0] S_OP_002 = 4;
    localparam [STATE_W-1:0] S_OP_003 = 5;
    localparam [STATE_W-1:0] S_OP_004 = 6;
    localparam [STATE_W-1:0] S_OP_005 = 7;
    localparam [STATE_W-1:0] S_OP_006 = 8;
    localparam [STATE_W-1:0] S_OP_007 = 9;
    localparam [STATE_W-1:0] S_OP_008 = 10;
    localparam [STATE_W-1:0] S_OP_009 = 11;
    localparam [STATE_W-1:0] S_OP_010 = 12;
    localparam [STATE_W-1:0] S_OP_011 = 13;
    localparam [STATE_W-1:0] S_OP_012 = 14;
    localparam [STATE_W-1:0] S_OP_013 = 15;
    localparam [STATE_W-1:0] S_OP_014 = 16;
    localparam [STATE_W-1:0] S_OP_015 = 17;
    localparam [STATE_W-1:0] S_OP_016 = 18;
    localparam [STATE_W-1:0] S_OP_017 = 19;
    localparam [STATE_W-1:0] S_OP_018 = 20;
    localparam [STATE_W-1:0] S_OP_019 = 21;
    localparam [STATE_W-1:0] S_OP_020 = 22;
    localparam [STATE_W-1:0] S_OP_021 = 23;
    localparam [STATE_W-1:0] S_OP_022 = 24;
    localparam [STATE_W-1:0] S_OP_023 = 25;
    localparam [STATE_W-1:0] S_OP_024 = 26;
    localparam [STATE_W-1:0] S_OP_025 = 27;
    localparam [STATE_W-1:0] S_OP_026 = 28;
    localparam [STATE_W-1:0] S_OP_027 = 29;
    localparam [STATE_W-1:0] S_OP_028 = 30;
    localparam [STATE_W-1:0] S_OP_029 = 31;
    localparam [STATE_W-1:0] S_OP_030 = 32;
    localparam [STATE_W-1:0] S_OP_031 = 33;
    localparam [STATE_W-1:0] S_OP_032 = 34;
    localparam [STATE_W-1:0] S_OP_033 = 35;
    localparam [STATE_W-1:0] S_OP_034 = 36;
    localparam [STATE_W-1:0] S_OP_035 = 37;
    localparam [STATE_W-1:0] S_OP_036 = 38;
    localparam [STATE_W-1:0] S_OP_037 = 39;
    localparam [STATE_W-1:0] S_OP_038 = 40;
    localparam [STATE_W-1:0] S_OP_039 = 41;
    localparam [STATE_W-1:0] S_OP_040 = 42;
    localparam [STATE_W-1:0] S_OP_041 = 43;
    localparam [STATE_W-1:0] S_OP_042 = 44;
    localparam [STATE_W-1:0] S_OP_043 = 45;
    localparam [STATE_W-1:0] S_OP_044 = 46;
    localparam [STATE_W-1:0] S_OP_045 = 47;
    localparam [STATE_W-1:0] S_OP_046 = 48;
    localparam [STATE_W-1:0] S_OP_047 = 49;
    localparam [STATE_W-1:0] S_OP_048 = 50;
    localparam [STATE_W-1:0] S_OP_049 = 51;
    localparam [STATE_W-1:0] S_OP_050 = 52;
    localparam [STATE_W-1:0] S_OP_051 = 53;
    localparam [STATE_W-1:0] S_OP_052 = 54;
    localparam [STATE_W-1:0] S_OP_053 = 55;
    localparam [STATE_W-1:0] S_OP_054 = 56;
    localparam [STATE_W-1:0] S_OP_055 = 57;
    localparam [STATE_W-1:0] S_OP_056 = 58;
    localparam [STATE_W-1:0] S_OP_057 = 59;
    localparam [STATE_W-1:0] S_OP_058 = 60;
    localparam [STATE_W-1:0] S_OP_059 = 61;
    localparam [STATE_W-1:0] S_OP_060 = 62;
    localparam [STATE_W-1:0] S_OP_061 = 63;
    localparam [STATE_W-1:0] S_OP_062 = 64;
    localparam [STATE_W-1:0] S_OP_063 = 65;
    localparam [STATE_W-1:0] S_OP_064 = 66;
    localparam [STATE_W-1:0] S_OP_065 = 67;
    localparam [STATE_W-1:0] S_OP_066 = 68;
    localparam [STATE_W-1:0] S_OP_067 = 69;
    localparam [STATE_W-1:0] S_OP_068 = 70;
    localparam [STATE_W-1:0] S_OP_069 = 71;
    localparam [STATE_W-1:0] S_OP_070 = 72;
    localparam [STATE_W-1:0] S_OP_071 = 73;
    localparam [STATE_W-1:0] S_OP_072 = 74;
    localparam [STATE_W-1:0] S_OP_073 = 75;
    localparam [STATE_W-1:0] S_OP_074 = 76;
    localparam [STATE_W-1:0] S_OP_075 = 77;
    localparam [STATE_W-1:0] S_OP_076 = 78;
    localparam [STATE_W-1:0] S_OP_077 = 79;
    localparam [STATE_W-1:0] S_OP_078 = 80;
    localparam [STATE_W-1:0] S_OP_079 = 81;
    localparam [STATE_W-1:0] S_OP_080 = 82;
    localparam [STATE_W-1:0] S_OP_081 = 83;
    localparam [STATE_W-1:0] S_OP_082 = 84;
    localparam [STATE_W-1:0] S_OP_083 = 85;
    localparam [STATE_W-1:0] S_OP_084 = 86;
    localparam [STATE_W-1:0] S_OP_085 = 87;
    localparam [STATE_W-1:0] S_OP_086 = 88;
    localparam [STATE_W-1:0] S_OP_087 = 89;
    localparam [STATE_W-1:0] S_OP_088 = 90;
    localparam [STATE_W-1:0] S_OP_089 = 91;
    localparam [STATE_W-1:0] S_OP_090 = 92;
    localparam [STATE_W-1:0] S_OP_091 = 93;
    localparam [STATE_W-1:0] S_OP_092 = 94;
    localparam [STATE_W-1:0] S_OP_093 = 95;
    localparam [STATE_W-1:0] S_OP_094 = 96;
    localparam [STATE_W-1:0] S_OP_095 = 97;
    localparam [STATE_W-1:0] S_OP_096 = 98;
    localparam [STATE_W-1:0] S_OP_097 = 99;
    localparam [STATE_W-1:0] S_OP_098 = 100;
    localparam [STATE_W-1:0] S_OP_099 = 101;
    localparam [STATE_W-1:0] S_OP_100 = 102;
    localparam [STATE_W-1:0] S_OP_101 = 103;
    localparam [STATE_W-1:0] S_OP_102 = 104;
    localparam [STATE_W-1:0] S_OP_103 = 105;
    localparam [STATE_W-1:0] S_OP_104 = 106;
    localparam [STATE_W-1:0] S_OP_105 = 107;
    localparam [STATE_W-1:0] S_OP_106 = 108;
    localparam [STATE_W-1:0] S_OP_107 = 109;
    localparam [STATE_W-1:0] S_OP_108 = 110;
    localparam [STATE_W-1:0] S_OP_109 = 111;
    localparam [STATE_W-1:0] S_OP_110 = 112;
    localparam [STATE_W-1:0] S_OP_111 = 113;
    localparam [STATE_W-1:0] S_DONE = 114;

    reg [STATE_W-1:0] state;
    reg [15:0] frozen_mask_reg;

    reg signed [W_INT-1:0] L0;
    reg signed [W_INT-1:0] L1;
    reg signed [W_INT-1:0] L2;
    reg signed [W_INT-1:0] L3;
    reg signed [W_INT-1:0] L4;
    reg signed [W_INT-1:0] L5;
    reg signed [W_INT-1:0] L6;
    reg signed [W_INT-1:0] L7;
    reg signed [W_INT-1:0] L8;
    reg signed [W_INT-1:0] L9;
    reg signed [W_INT-1:0] L10;
    reg signed [W_INT-1:0] L11;
    reg signed [W_INT-1:0] L12;
    reg signed [W_INT-1:0] L13;
    reg signed [W_INT-1:0] L14;
    reg signed [W_INT-1:0] L15;

    reg signed [W_INT-1:0] llr_NLLL_L0;
    reg signed [W_INT-1:0] llr_NLLL_R0;
    reg signed [W_INT-1:0] llr_NLLR_L0;
    reg signed [W_INT-1:0] llr_NLLR_R0;
    reg signed [W_INT-1:0] llr_NLL_L0;
    reg signed [W_INT-1:0] llr_NLL_L1;
    reg signed [W_INT-1:0] llr_NLL_R0;
    reg signed [W_INT-1:0] llr_NLL_R1;
    reg signed [W_INT-1:0] llr_NLRL_L0;
    reg signed [W_INT-1:0] llr_NLRL_R0;
    reg signed [W_INT-1:0] llr_NLRR_L0;
    reg signed [W_INT-1:0] llr_NLRR_R0;
    reg signed [W_INT-1:0] llr_NLR_L0;
    reg signed [W_INT-1:0] llr_NLR_L1;
    reg signed [W_INT-1:0] llr_NLR_R0;
    reg signed [W_INT-1:0] llr_NLR_R1;
    reg signed [W_INT-1:0] llr_NL_L0;
    reg signed [W_INT-1:0] llr_NL_L1;
    reg signed [W_INT-1:0] llr_NL_L2;
    reg signed [W_INT-1:0] llr_NL_L3;
    reg signed [W_INT-1:0] llr_NL_R0;
    reg signed [W_INT-1:0] llr_NL_R1;
    reg signed [W_INT-1:0] llr_NL_R2;
    reg signed [W_INT-1:0] llr_NL_R3;
    reg signed [W_INT-1:0] llr_NRLL_L0;
    reg signed [W_INT-1:0] llr_NRLL_R0;
    reg signed [W_INT-1:0] llr_NRLR_L0;
    reg signed [W_INT-1:0] llr_NRLR_R0;
    reg signed [W_INT-1:0] llr_NRL_L0;
    reg signed [W_INT-1:0] llr_NRL_L1;
    reg signed [W_INT-1:0] llr_NRL_R0;
    reg signed [W_INT-1:0] llr_NRL_R1;
    reg signed [W_INT-1:0] llr_NRRL_L0;
    reg signed [W_INT-1:0] llr_NRRL_R0;
    reg signed [W_INT-1:0] llr_NRRR_L0;
    reg signed [W_INT-1:0] llr_NRRR_R0;
    reg signed [W_INT-1:0] llr_NRR_L0;
    reg signed [W_INT-1:0] llr_NRR_L1;
    reg signed [W_INT-1:0] llr_NRR_R0;
    reg signed [W_INT-1:0] llr_NRR_R1;
    reg signed [W_INT-1:0] llr_NR_L0;
    reg signed [W_INT-1:0] llr_NR_L1;
    reg signed [W_INT-1:0] llr_NR_L2;
    reg signed [W_INT-1:0] llr_NR_L3;
    reg signed [W_INT-1:0] llr_NR_R0;
    reg signed [W_INT-1:0] llr_NR_R1;
    reg signed [W_INT-1:0] llr_NR_R2;
    reg signed [W_INT-1:0] llr_NR_R3;
    reg signed [W_INT-1:0] llr_ROOT_L0;
    reg signed [W_INT-1:0] llr_ROOT_L1;
    reg signed [W_INT-1:0] llr_ROOT_L2;
    reg signed [W_INT-1:0] llr_ROOT_L3;
    reg signed [W_INT-1:0] llr_ROOT_L4;
    reg signed [W_INT-1:0] llr_ROOT_L5;
    reg signed [W_INT-1:0] llr_ROOT_L6;
    reg signed [W_INT-1:0] llr_ROOT_L7;
    reg signed [W_INT-1:0] llr_ROOT_R0;
    reg signed [W_INT-1:0] llr_ROOT_R1;
    reg signed [W_INT-1:0] llr_ROOT_R2;
    reg signed [W_INT-1:0] llr_ROOT_R3;
    reg signed [W_INT-1:0] llr_ROOT_R4;
    reg signed [W_INT-1:0] llr_ROOT_R5;
    reg signed [W_INT-1:0] llr_ROOT_R6;
    reg signed [W_INT-1:0] llr_ROOT_R7;

    reg p_NLLL_0;
    reg p_NLLR_0;
    reg p_NLL_0;
    reg p_NLL_1;
    reg p_NLRL_0;
    reg p_NLRR_0;
    reg p_NLR_0;
    reg p_NLR_1;
    reg p_NL_0;
    reg p_NL_1;
    reg p_NL_2;
    reg p_NL_3;
    reg p_NRLL_0;
    reg p_NRLR_0;
    reg p_NRL_0;
    reg p_NRL_1;
    reg p_NRRL_0;
    reg p_NRRR_0;
    reg p_NRR_0;
    reg p_NRR_1;
    reg p_NR_0;
    reg p_NR_1;
    reg p_NR_2;
    reg p_NR_3;
    reg p_ROOT_0;
    reg p_ROOT_1;
    reg p_ROOT_2;
    reg p_ROOT_3;
    reg p_ROOT_4;
    reg p_ROOT_5;
    reg p_ROOT_6;
    reg p_ROOT_7;

    reg u0;
    reg u1;
    reg u2;
    reg u3;
    reg u4;
    reg u5;
    reg u6;
    reg u7;
    reg u8;
    reg u9;
    reg u10;
    reg u11;
    reg u12;
    reg u13;
    reg u14;
    reg u15;

    reg signed [W_INT-1:0] fu_a;
    reg signed [W_INT-1:0] fu_b;
    reg                    fu_is_g;
    reg                    fu_g_bit;
    wire signed [W_INT-1:0] fu_y;

    function signed [W_INT-1:0] f_func;
        input signed [W_INT-1:0] a;
        input signed [W_INT-1:0] b;
        reg signed [W_INT-1:0] abs_a;
        reg signed [W_INT-1:0] abs_b;
        reg signed [W_INT-1:0] mag;
        reg negative;
        begin
            abs_a = a[W_INT-1] ? -a : a;
            abs_b = b[W_INT-1] ? -b : b;
            mag = (abs_a < abs_b) ? abs_a : abs_b;
            negative = a[W_INT-1] ^ b[W_INT-1];
            f_func = negative ? -mag : mag;
        end
    endfunction

    function signed [W_INT-1:0] g_func;
        input signed [W_INT-1:0] a;
        input signed [W_INT-1:0] b;
        input u;
        begin
            g_func = (u == 1'b0) ? (b + a) : (b - a);
        end
    endfunction

    function hard_decision;
        input signed [W_INT-1:0] llr;
        begin
            hard_decision = (llr < 0) ? 1'b1 : 1'b0;
        end
    endfunction

    assign fu_y = fu_is_g ? g_func(fu_a, fu_b, fu_g_bit)
                           : f_func(fu_a, fu_b);

    always @* begin
        fu_a = {W_INT{1'b0}};
        fu_b = {W_INT{1'b0}};
        fu_is_g = 1'b0;
        fu_g_bit = 1'b0;

        case (state)
            S_OP_000: begin
                fu_a = L0;
                fu_b = L8;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_001: begin
                fu_a = L1;
                fu_b = L9;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_002: begin
                fu_a = L2;
                fu_b = L10;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_003: begin
                fu_a = L3;
                fu_b = L11;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_004: begin
                fu_a = L4;
                fu_b = L12;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_005: begin
                fu_a = L5;
                fu_b = L13;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_006: begin
                fu_a = L6;
                fu_b = L14;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_007: begin
                fu_a = L7;
                fu_b = L15;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_008: begin
                fu_a = llr_ROOT_L0;
                fu_b = llr_ROOT_L4;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_009: begin
                fu_a = llr_ROOT_L1;
                fu_b = llr_ROOT_L5;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_010: begin
                fu_a = llr_ROOT_L2;
                fu_b = llr_ROOT_L6;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_011: begin
                fu_a = llr_ROOT_L3;
                fu_b = llr_ROOT_L7;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_012: begin
                fu_a = llr_NL_L0;
                fu_b = llr_NL_L2;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_013: begin
                fu_a = llr_NL_L1;
                fu_b = llr_NL_L3;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_014: begin
                fu_a = llr_NLL_L0;
                fu_b = llr_NLL_L1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_017: begin
                fu_a = llr_NLL_L0;
                fu_b = llr_NLL_L1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLLL_0;
            end
            S_OP_021: begin
                fu_a = llr_NL_L0;
                fu_b = llr_NL_L2;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLL_0;
            end
            S_OP_022: begin
                fu_a = llr_NL_L1;
                fu_b = llr_NL_L3;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLL_1;
            end
            S_OP_023: begin
                fu_a = llr_NLL_R0;
                fu_b = llr_NLL_R1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_026: begin
                fu_a = llr_NLL_R0;
                fu_b = llr_NLL_R1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLLR_0;
            end
            S_OP_032: begin
                fu_a = llr_ROOT_L0;
                fu_b = llr_ROOT_L4;
                fu_is_g = 1'b1;
                fu_g_bit = p_NL_0;
            end
            S_OP_033: begin
                fu_a = llr_ROOT_L1;
                fu_b = llr_ROOT_L5;
                fu_is_g = 1'b1;
                fu_g_bit = p_NL_1;
            end
            S_OP_034: begin
                fu_a = llr_ROOT_L2;
                fu_b = llr_ROOT_L6;
                fu_is_g = 1'b1;
                fu_g_bit = p_NL_2;
            end
            S_OP_035: begin
                fu_a = llr_ROOT_L3;
                fu_b = llr_ROOT_L7;
                fu_is_g = 1'b1;
                fu_g_bit = p_NL_3;
            end
            S_OP_036: begin
                fu_a = llr_NL_R0;
                fu_b = llr_NL_R2;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_037: begin
                fu_a = llr_NL_R1;
                fu_b = llr_NL_R3;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_038: begin
                fu_a = llr_NLR_L0;
                fu_b = llr_NLR_L1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_041: begin
                fu_a = llr_NLR_L0;
                fu_b = llr_NLR_L1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLRL_0;
            end
            S_OP_045: begin
                fu_a = llr_NL_R0;
                fu_b = llr_NL_R2;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLR_0;
            end
            S_OP_046: begin
                fu_a = llr_NL_R1;
                fu_b = llr_NL_R3;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLR_1;
            end
            S_OP_047: begin
                fu_a = llr_NLR_R0;
                fu_b = llr_NLR_R1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_050: begin
                fu_a = llr_NLR_R0;
                fu_b = llr_NLR_R1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NLRR_0;
            end
            S_OP_060: begin
                fu_a = L0;
                fu_b = L8;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_0;
            end
            S_OP_061: begin
                fu_a = L1;
                fu_b = L9;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_1;
            end
            S_OP_062: begin
                fu_a = L2;
                fu_b = L10;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_2;
            end
            S_OP_063: begin
                fu_a = L3;
                fu_b = L11;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_3;
            end
            S_OP_064: begin
                fu_a = L4;
                fu_b = L12;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_4;
            end
            S_OP_065: begin
                fu_a = L5;
                fu_b = L13;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_5;
            end
            S_OP_066: begin
                fu_a = L6;
                fu_b = L14;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_6;
            end
            S_OP_067: begin
                fu_a = L7;
                fu_b = L15;
                fu_is_g = 1'b1;
                fu_g_bit = p_ROOT_7;
            end
            S_OP_068: begin
                fu_a = llr_ROOT_R0;
                fu_b = llr_ROOT_R4;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_069: begin
                fu_a = llr_ROOT_R1;
                fu_b = llr_ROOT_R5;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_070: begin
                fu_a = llr_ROOT_R2;
                fu_b = llr_ROOT_R6;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_071: begin
                fu_a = llr_ROOT_R3;
                fu_b = llr_ROOT_R7;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_072: begin
                fu_a = llr_NR_L0;
                fu_b = llr_NR_L2;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_073: begin
                fu_a = llr_NR_L1;
                fu_b = llr_NR_L3;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_074: begin
                fu_a = llr_NRL_L0;
                fu_b = llr_NRL_L1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_077: begin
                fu_a = llr_NRL_L0;
                fu_b = llr_NRL_L1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRLL_0;
            end
            S_OP_081: begin
                fu_a = llr_NR_L0;
                fu_b = llr_NR_L2;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRL_0;
            end
            S_OP_082: begin
                fu_a = llr_NR_L1;
                fu_b = llr_NR_L3;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRL_1;
            end
            S_OP_083: begin
                fu_a = llr_NRL_R0;
                fu_b = llr_NRL_R1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_086: begin
                fu_a = llr_NRL_R0;
                fu_b = llr_NRL_R1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRLR_0;
            end
            S_OP_092: begin
                fu_a = llr_ROOT_R0;
                fu_b = llr_ROOT_R4;
                fu_is_g = 1'b1;
                fu_g_bit = p_NR_0;
            end
            S_OP_093: begin
                fu_a = llr_ROOT_R1;
                fu_b = llr_ROOT_R5;
                fu_is_g = 1'b1;
                fu_g_bit = p_NR_1;
            end
            S_OP_094: begin
                fu_a = llr_ROOT_R2;
                fu_b = llr_ROOT_R6;
                fu_is_g = 1'b1;
                fu_g_bit = p_NR_2;
            end
            S_OP_095: begin
                fu_a = llr_ROOT_R3;
                fu_b = llr_ROOT_R7;
                fu_is_g = 1'b1;
                fu_g_bit = p_NR_3;
            end
            S_OP_096: begin
                fu_a = llr_NR_R0;
                fu_b = llr_NR_R2;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_097: begin
                fu_a = llr_NR_R1;
                fu_b = llr_NR_R3;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_098: begin
                fu_a = llr_NRR_L0;
                fu_b = llr_NRR_L1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_101: begin
                fu_a = llr_NRR_L0;
                fu_b = llr_NRR_L1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRRL_0;
            end
            S_OP_105: begin
                fu_a = llr_NR_R0;
                fu_b = llr_NR_R2;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRR_0;
            end
            S_OP_106: begin
                fu_a = llr_NR_R1;
                fu_b = llr_NR_R3;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRR_1;
            end
            S_OP_107: begin
                fu_a = llr_NRR_R0;
                fu_b = llr_NRR_R1;
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
            S_OP_110: begin
                fu_a = llr_NRR_R0;
                fu_b = llr_NRR_R1;
                fu_is_g = 1'b1;
                fu_g_bit = p_NRRR_0;
            end
            default: begin
                fu_a = {W_INT{1'b0}};
                fu_b = {W_INT{1'b0}};
                fu_is_g = 1'b0;
                fu_g_bit = 1'b0;
            end
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state <= S_IDLE;
            frozen_mask_reg <= 16'd0;
            u_hat <= 16'd0;
            busy <= 1'b0;
            done <= 1'b0;
            L0 <= {W_INT{1'b0}};
            L1 <= {W_INT{1'b0}};
            L2 <= {W_INT{1'b0}};
            L3 <= {W_INT{1'b0}};
            L4 <= {W_INT{1'b0}};
            L5 <= {W_INT{1'b0}};
            L6 <= {W_INT{1'b0}};
            L7 <= {W_INT{1'b0}};
            L8 <= {W_INT{1'b0}};
            L9 <= {W_INT{1'b0}};
            L10 <= {W_INT{1'b0}};
            L11 <= {W_INT{1'b0}};
            L12 <= {W_INT{1'b0}};
            L13 <= {W_INT{1'b0}};
            L14 <= {W_INT{1'b0}};
            L15 <= {W_INT{1'b0}};
            llr_NLLL_L0 <= {W_INT{1'b0}};
            llr_NLLL_R0 <= {W_INT{1'b0}};
            llr_NLLR_L0 <= {W_INT{1'b0}};
            llr_NLLR_R0 <= {W_INT{1'b0}};
            llr_NLL_L0 <= {W_INT{1'b0}};
            llr_NLL_L1 <= {W_INT{1'b0}};
            llr_NLL_R0 <= {W_INT{1'b0}};
            llr_NLL_R1 <= {W_INT{1'b0}};
            llr_NLRL_L0 <= {W_INT{1'b0}};
            llr_NLRL_R0 <= {W_INT{1'b0}};
            llr_NLRR_L0 <= {W_INT{1'b0}};
            llr_NLRR_R0 <= {W_INT{1'b0}};
            llr_NLR_L0 <= {W_INT{1'b0}};
            llr_NLR_L1 <= {W_INT{1'b0}};
            llr_NLR_R0 <= {W_INT{1'b0}};
            llr_NLR_R1 <= {W_INT{1'b0}};
            llr_NL_L0 <= {W_INT{1'b0}};
            llr_NL_L1 <= {W_INT{1'b0}};
            llr_NL_L2 <= {W_INT{1'b0}};
            llr_NL_L3 <= {W_INT{1'b0}};
            llr_NL_R0 <= {W_INT{1'b0}};
            llr_NL_R1 <= {W_INT{1'b0}};
            llr_NL_R2 <= {W_INT{1'b0}};
            llr_NL_R3 <= {W_INT{1'b0}};
            llr_NRLL_L0 <= {W_INT{1'b0}};
            llr_NRLL_R0 <= {W_INT{1'b0}};
            llr_NRLR_L0 <= {W_INT{1'b0}};
            llr_NRLR_R0 <= {W_INT{1'b0}};
            llr_NRL_L0 <= {W_INT{1'b0}};
            llr_NRL_L1 <= {W_INT{1'b0}};
            llr_NRL_R0 <= {W_INT{1'b0}};
            llr_NRL_R1 <= {W_INT{1'b0}};
            llr_NRRL_L0 <= {W_INT{1'b0}};
            llr_NRRL_R0 <= {W_INT{1'b0}};
            llr_NRRR_L0 <= {W_INT{1'b0}};
            llr_NRRR_R0 <= {W_INT{1'b0}};
            llr_NRR_L0 <= {W_INT{1'b0}};
            llr_NRR_L1 <= {W_INT{1'b0}};
            llr_NRR_R0 <= {W_INT{1'b0}};
            llr_NRR_R1 <= {W_INT{1'b0}};
            llr_NR_L0 <= {W_INT{1'b0}};
            llr_NR_L1 <= {W_INT{1'b0}};
            llr_NR_L2 <= {W_INT{1'b0}};
            llr_NR_L3 <= {W_INT{1'b0}};
            llr_NR_R0 <= {W_INT{1'b0}};
            llr_NR_R1 <= {W_INT{1'b0}};
            llr_NR_R2 <= {W_INT{1'b0}};
            llr_NR_R3 <= {W_INT{1'b0}};
            llr_ROOT_L0 <= {W_INT{1'b0}};
            llr_ROOT_L1 <= {W_INT{1'b0}};
            llr_ROOT_L2 <= {W_INT{1'b0}};
            llr_ROOT_L3 <= {W_INT{1'b0}};
            llr_ROOT_L4 <= {W_INT{1'b0}};
            llr_ROOT_L5 <= {W_INT{1'b0}};
            llr_ROOT_L6 <= {W_INT{1'b0}};
            llr_ROOT_L7 <= {W_INT{1'b0}};
            llr_ROOT_R0 <= {W_INT{1'b0}};
            llr_ROOT_R1 <= {W_INT{1'b0}};
            llr_ROOT_R2 <= {W_INT{1'b0}};
            llr_ROOT_R3 <= {W_INT{1'b0}};
            llr_ROOT_R4 <= {W_INT{1'b0}};
            llr_ROOT_R5 <= {W_INT{1'b0}};
            llr_ROOT_R6 <= {W_INT{1'b0}};
            llr_ROOT_R7 <= {W_INT{1'b0}};
            p_NLLL_0 <= 1'b0;
            p_NLLR_0 <= 1'b0;
            p_NLL_0 <= 1'b0;
            p_NLL_1 <= 1'b0;
            p_NLRL_0 <= 1'b0;
            p_NLRR_0 <= 1'b0;
            p_NLR_0 <= 1'b0;
            p_NLR_1 <= 1'b0;
            p_NL_0 <= 1'b0;
            p_NL_1 <= 1'b0;
            p_NL_2 <= 1'b0;
            p_NL_3 <= 1'b0;
            p_NRLL_0 <= 1'b0;
            p_NRLR_0 <= 1'b0;
            p_NRL_0 <= 1'b0;
            p_NRL_1 <= 1'b0;
            p_NRRL_0 <= 1'b0;
            p_NRRR_0 <= 1'b0;
            p_NRR_0 <= 1'b0;
            p_NRR_1 <= 1'b0;
            p_NR_0 <= 1'b0;
            p_NR_1 <= 1'b0;
            p_NR_2 <= 1'b0;
            p_NR_3 <= 1'b0;
            p_ROOT_0 <= 1'b0;
            p_ROOT_1 <= 1'b0;
            p_ROOT_2 <= 1'b0;
            p_ROOT_3 <= 1'b0;
            p_ROOT_4 <= 1'b0;
            p_ROOT_5 <= 1'b0;
            p_ROOT_6 <= 1'b0;
            p_ROOT_7 <= 1'b0;
            u0 <= 1'b0;
            u1 <= 1'b0;
            u2 <= 1'b0;
            u3 <= 1'b0;
            u4 <= 1'b0;
            u5 <= 1'b0;
            u6 <= 1'b0;
            u7 <= 1'b0;
            u8 <= 1'b0;
            u9 <= 1'b0;
            u10 <= 1'b0;
            u11 <= 1'b0;
            u12 <= 1'b0;
            u13 <= 1'b0;
            u14 <= 1'b0;
            u15 <= 1'b0;
        end else begin
            done <= 1'b0;

            case (state)
                S_IDLE: begin
                    busy <= 1'b0;
                    if (start) begin
                        busy <= 1'b1;
                        state <= S_LOAD;
                    end
                end

                S_LOAD: begin
                    busy <= 1'b1;
                    frozen_mask_reg <= frozen_mask;
                    L0 <= {{(W_INT-W_IN){llr0[W_IN-1]}}, llr0};
                    L1 <= {{(W_INT-W_IN){llr1[W_IN-1]}}, llr1};
                    L2 <= {{(W_INT-W_IN){llr2[W_IN-1]}}, llr2};
                    L3 <= {{(W_INT-W_IN){llr3[W_IN-1]}}, llr3};
                    L4 <= {{(W_INT-W_IN){llr4[W_IN-1]}}, llr4};
                    L5 <= {{(W_INT-W_IN){llr5[W_IN-1]}}, llr5};
                    L6 <= {{(W_INT-W_IN){llr6[W_IN-1]}}, llr6};
                    L7 <= {{(W_INT-W_IN){llr7[W_IN-1]}}, llr7};
                    L8 <= {{(W_INT-W_IN){llr8[W_IN-1]}}, llr8};
                    L9 <= {{(W_INT-W_IN){llr9[W_IN-1]}}, llr9};
                    L10 <= {{(W_INT-W_IN){llr10[W_IN-1]}}, llr10};
                    L11 <= {{(W_INT-W_IN){llr11[W_IN-1]}}, llr11};
                    L12 <= {{(W_INT-W_IN){llr12[W_IN-1]}}, llr12};
                    L13 <= {{(W_INT-W_IN){llr13[W_IN-1]}}, llr13};
                    L14 <= {{(W_INT-W_IN){llr14[W_IN-1]}}, llr14};
                    L15 <= {{(W_INT-W_IN){llr15[W_IN-1]}}, llr15};
                    state <= S_OP_000;
                end

                S_OP_000: begin
                    llr_ROOT_L0 <= fu_y;
                    state <= S_OP_001;
                end

                S_OP_001: begin
                    llr_ROOT_L1 <= fu_y;
                    state <= S_OP_002;
                end

                S_OP_002: begin
                    llr_ROOT_L2 <= fu_y;
                    state <= S_OP_003;
                end

                S_OP_003: begin
                    llr_ROOT_L3 <= fu_y;
                    state <= S_OP_004;
                end

                S_OP_004: begin
                    llr_ROOT_L4 <= fu_y;
                    state <= S_OP_005;
                end

                S_OP_005: begin
                    llr_ROOT_L5 <= fu_y;
                    state <= S_OP_006;
                end

                S_OP_006: begin
                    llr_ROOT_L6 <= fu_y;
                    state <= S_OP_007;
                end

                S_OP_007: begin
                    llr_ROOT_L7 <= fu_y;
                    state <= S_OP_008;
                end

                S_OP_008: begin
                    llr_NL_L0 <= fu_y;
                    state <= S_OP_009;
                end

                S_OP_009: begin
                    llr_NL_L1 <= fu_y;
                    state <= S_OP_010;
                end

                S_OP_010: begin
                    llr_NL_L2 <= fu_y;
                    state <= S_OP_011;
                end

                S_OP_011: begin
                    llr_NL_L3 <= fu_y;
                    state <= S_OP_012;
                end

                S_OP_012: begin
                    llr_NLL_L0 <= fu_y;
                    state <= S_OP_013;
                end

                S_OP_013: begin
                    llr_NLL_L1 <= fu_y;
                    state <= S_OP_014;
                end

                S_OP_014: begin
                    llr_NLLL_L0 <= fu_y;
                    state <= S_OP_015;
                end

                S_OP_015: begin
                    u0 <= frozen_mask_reg[0] ? 1'b0 : hard_decision(llr_NLLL_L0);
                    state <= S_OP_016;
                end

                S_OP_016: begin
                    p_NLLL_0 <= u0;
                    state <= S_OP_017;
                end

                S_OP_017: begin
                    llr_NLLL_R0 <= fu_y;
                    state <= S_OP_018;
                end

                S_OP_018: begin
                    u1 <= frozen_mask_reg[1] ? 1'b0 : hard_decision(llr_NLLL_R0);
                    state <= S_OP_019;
                end

                S_OP_019: begin
                    p_NLL_0 <= u0 ^ u1;
                    state <= S_OP_020;
                end

                S_OP_020: begin
                    p_NLL_1 <= u1;
                    state <= S_OP_021;
                end

                S_OP_021: begin
                    llr_NLL_R0 <= fu_y;
                    state <= S_OP_022;
                end

                S_OP_022: begin
                    llr_NLL_R1 <= fu_y;
                    state <= S_OP_023;
                end

                S_OP_023: begin
                    llr_NLLR_L0 <= fu_y;
                    state <= S_OP_024;
                end

                S_OP_024: begin
                    u2 <= frozen_mask_reg[2] ? 1'b0 : hard_decision(llr_NLLR_L0);
                    state <= S_OP_025;
                end

                S_OP_025: begin
                    p_NLLR_0 <= u2;
                    state <= S_OP_026;
                end

                S_OP_026: begin
                    llr_NLLR_R0 <= fu_y;
                    state <= S_OP_027;
                end

                S_OP_027: begin
                    u3 <= frozen_mask_reg[3] ? 1'b0 : hard_decision(llr_NLLR_R0);
                    state <= S_OP_028;
                end

                S_OP_028: begin
                    p_NL_0 <= u0 ^ u1 ^ u2 ^ u3;
                    state <= S_OP_029;
                end

                S_OP_029: begin
                    p_NL_1 <= u1 ^ u3;
                    state <= S_OP_030;
                end

                S_OP_030: begin
                    p_NL_2 <= u2 ^ u3;
                    state <= S_OP_031;
                end

                S_OP_031: begin
                    p_NL_3 <= u3;
                    state <= S_OP_032;
                end

                S_OP_032: begin
                    llr_NL_R0 <= fu_y;
                    state <= S_OP_033;
                end

                S_OP_033: begin
                    llr_NL_R1 <= fu_y;
                    state <= S_OP_034;
                end

                S_OP_034: begin
                    llr_NL_R2 <= fu_y;
                    state <= S_OP_035;
                end

                S_OP_035: begin
                    llr_NL_R3 <= fu_y;
                    state <= S_OP_036;
                end

                S_OP_036: begin
                    llr_NLR_L0 <= fu_y;
                    state <= S_OP_037;
                end

                S_OP_037: begin
                    llr_NLR_L1 <= fu_y;
                    state <= S_OP_038;
                end

                S_OP_038: begin
                    llr_NLRL_L0 <= fu_y;
                    state <= S_OP_039;
                end

                S_OP_039: begin
                    u4 <= frozen_mask_reg[4] ? 1'b0 : hard_decision(llr_NLRL_L0);
                    state <= S_OP_040;
                end

                S_OP_040: begin
                    p_NLRL_0 <= u4;
                    state <= S_OP_041;
                end

                S_OP_041: begin
                    llr_NLRL_R0 <= fu_y;
                    state <= S_OP_042;
                end

                S_OP_042: begin
                    u5 <= frozen_mask_reg[5] ? 1'b0 : hard_decision(llr_NLRL_R0);
                    state <= S_OP_043;
                end

                S_OP_043: begin
                    p_NLR_0 <= u4 ^ u5;
                    state <= S_OP_044;
                end

                S_OP_044: begin
                    p_NLR_1 <= u5;
                    state <= S_OP_045;
                end

                S_OP_045: begin
                    llr_NLR_R0 <= fu_y;
                    state <= S_OP_046;
                end

                S_OP_046: begin
                    llr_NLR_R1 <= fu_y;
                    state <= S_OP_047;
                end

                S_OP_047: begin
                    llr_NLRR_L0 <= fu_y;
                    state <= S_OP_048;
                end

                S_OP_048: begin
                    u6 <= frozen_mask_reg[6] ? 1'b0 : hard_decision(llr_NLRR_L0);
                    state <= S_OP_049;
                end

                S_OP_049: begin
                    p_NLRR_0 <= u6;
                    state <= S_OP_050;
                end

                S_OP_050: begin
                    llr_NLRR_R0 <= fu_y;
                    state <= S_OP_051;
                end

                S_OP_051: begin
                    u7 <= frozen_mask_reg[7] ? 1'b0 : hard_decision(llr_NLRR_R0);
                    state <= S_OP_052;
                end

                S_OP_052: begin
                    p_ROOT_0 <= u0 ^ u1 ^ u2 ^ u3 ^ u4 ^ u5 ^ u6 ^ u7;
                    state <= S_OP_053;
                end

                S_OP_053: begin
                    p_ROOT_1 <= u1 ^ u3 ^ u5 ^ u7;
                    state <= S_OP_054;
                end

                S_OP_054: begin
                    p_ROOT_2 <= u2 ^ u3 ^ u6 ^ u7;
                    state <= S_OP_055;
                end

                S_OP_055: begin
                    p_ROOT_3 <= u3 ^ u7;
                    state <= S_OP_056;
                end

                S_OP_056: begin
                    p_ROOT_4 <= u4 ^ u5 ^ u6 ^ u7;
                    state <= S_OP_057;
                end

                S_OP_057: begin
                    p_ROOT_5 <= u5 ^ u7;
                    state <= S_OP_058;
                end

                S_OP_058: begin
                    p_ROOT_6 <= u6 ^ u7;
                    state <= S_OP_059;
                end

                S_OP_059: begin
                    p_ROOT_7 <= u7;
                    state <= S_OP_060;
                end

                S_OP_060: begin
                    llr_ROOT_R0 <= fu_y;
                    state <= S_OP_061;
                end

                S_OP_061: begin
                    llr_ROOT_R1 <= fu_y;
                    state <= S_OP_062;
                end

                S_OP_062: begin
                    llr_ROOT_R2 <= fu_y;
                    state <= S_OP_063;
                end

                S_OP_063: begin
                    llr_ROOT_R3 <= fu_y;
                    state <= S_OP_064;
                end

                S_OP_064: begin
                    llr_ROOT_R4 <= fu_y;
                    state <= S_OP_065;
                end

                S_OP_065: begin
                    llr_ROOT_R5 <= fu_y;
                    state <= S_OP_066;
                end

                S_OP_066: begin
                    llr_ROOT_R6 <= fu_y;
                    state <= S_OP_067;
                end

                S_OP_067: begin
                    llr_ROOT_R7 <= fu_y;
                    state <= S_OP_068;
                end

                S_OP_068: begin
                    llr_NR_L0 <= fu_y;
                    state <= S_OP_069;
                end

                S_OP_069: begin
                    llr_NR_L1 <= fu_y;
                    state <= S_OP_070;
                end

                S_OP_070: begin
                    llr_NR_L2 <= fu_y;
                    state <= S_OP_071;
                end

                S_OP_071: begin
                    llr_NR_L3 <= fu_y;
                    state <= S_OP_072;
                end

                S_OP_072: begin
                    llr_NRL_L0 <= fu_y;
                    state <= S_OP_073;
                end

                S_OP_073: begin
                    llr_NRL_L1 <= fu_y;
                    state <= S_OP_074;
                end

                S_OP_074: begin
                    llr_NRLL_L0 <= fu_y;
                    state <= S_OP_075;
                end

                S_OP_075: begin
                    u8 <= frozen_mask_reg[8] ? 1'b0 : hard_decision(llr_NRLL_L0);
                    state <= S_OP_076;
                end

                S_OP_076: begin
                    p_NRLL_0 <= u8;
                    state <= S_OP_077;
                end

                S_OP_077: begin
                    llr_NRLL_R0 <= fu_y;
                    state <= S_OP_078;
                end

                S_OP_078: begin
                    u9 <= frozen_mask_reg[9] ? 1'b0 : hard_decision(llr_NRLL_R0);
                    state <= S_OP_079;
                end

                S_OP_079: begin
                    p_NRL_0 <= u8 ^ u9;
                    state <= S_OP_080;
                end

                S_OP_080: begin
                    p_NRL_1 <= u9;
                    state <= S_OP_081;
                end

                S_OP_081: begin
                    llr_NRL_R0 <= fu_y;
                    state <= S_OP_082;
                end

                S_OP_082: begin
                    llr_NRL_R1 <= fu_y;
                    state <= S_OP_083;
                end

                S_OP_083: begin
                    llr_NRLR_L0 <= fu_y;
                    state <= S_OP_084;
                end

                S_OP_084: begin
                    u10 <= frozen_mask_reg[10] ? 1'b0 : hard_decision(llr_NRLR_L0);
                    state <= S_OP_085;
                end

                S_OP_085: begin
                    p_NRLR_0 <= u10;
                    state <= S_OP_086;
                end

                S_OP_086: begin
                    llr_NRLR_R0 <= fu_y;
                    state <= S_OP_087;
                end

                S_OP_087: begin
                    u11 <= frozen_mask_reg[11] ? 1'b0 : hard_decision(llr_NRLR_R0);
                    state <= S_OP_088;
                end

                S_OP_088: begin
                    p_NR_0 <= u8 ^ u9 ^ u10 ^ u11;
                    state <= S_OP_089;
                end

                S_OP_089: begin
                    p_NR_1 <= u9 ^ u11;
                    state <= S_OP_090;
                end

                S_OP_090: begin
                    p_NR_2 <= u10 ^ u11;
                    state <= S_OP_091;
                end

                S_OP_091: begin
                    p_NR_3 <= u11;
                    state <= S_OP_092;
                end

                S_OP_092: begin
                    llr_NR_R0 <= fu_y;
                    state <= S_OP_093;
                end

                S_OP_093: begin
                    llr_NR_R1 <= fu_y;
                    state <= S_OP_094;
                end

                S_OP_094: begin
                    llr_NR_R2 <= fu_y;
                    state <= S_OP_095;
                end

                S_OP_095: begin
                    llr_NR_R3 <= fu_y;
                    state <= S_OP_096;
                end

                S_OP_096: begin
                    llr_NRR_L0 <= fu_y;
                    state <= S_OP_097;
                end

                S_OP_097: begin
                    llr_NRR_L1 <= fu_y;
                    state <= S_OP_098;
                end

                S_OP_098: begin
                    llr_NRRL_L0 <= fu_y;
                    state <= S_OP_099;
                end

                S_OP_099: begin
                    u12 <= frozen_mask_reg[12] ? 1'b0 : hard_decision(llr_NRRL_L0);
                    state <= S_OP_100;
                end

                S_OP_100: begin
                    p_NRRL_0 <= u12;
                    state <= S_OP_101;
                end

                S_OP_101: begin
                    llr_NRRL_R0 <= fu_y;
                    state <= S_OP_102;
                end

                S_OP_102: begin
                    u13 <= frozen_mask_reg[13] ? 1'b0 : hard_decision(llr_NRRL_R0);
                    state <= S_OP_103;
                end

                S_OP_103: begin
                    p_NRR_0 <= u12 ^ u13;
                    state <= S_OP_104;
                end

                S_OP_104: begin
                    p_NRR_1 <= u13;
                    state <= S_OP_105;
                end

                S_OP_105: begin
                    llr_NRR_R0 <= fu_y;
                    state <= S_OP_106;
                end

                S_OP_106: begin
                    llr_NRR_R1 <= fu_y;
                    state <= S_OP_107;
                end

                S_OP_107: begin
                    llr_NRRR_L0 <= fu_y;
                    state <= S_OP_108;
                end

                S_OP_108: begin
                    u14 <= frozen_mask_reg[14] ? 1'b0 : hard_decision(llr_NRRR_L0);
                    state <= S_OP_109;
                end

                S_OP_109: begin
                    p_NRRR_0 <= u14;
                    state <= S_OP_110;
                end

                S_OP_110: begin
                    llr_NRRR_R0 <= fu_y;
                    state <= S_OP_111;
                end

                S_OP_111: begin
                    u15 <= frozen_mask_reg[15] ? 1'b0 : hard_decision(llr_NRRR_R0);
                    state <= S_DONE;
                end

                S_DONE: begin
                    u_hat[0] <= u0;
                    u_hat[1] <= u1;
                    u_hat[2] <= u2;
                    u_hat[3] <= u3;
                    u_hat[4] <= u4;
                    u_hat[5] <= u5;
                    u_hat[6] <= u6;
                    u_hat[7] <= u7;
                    u_hat[8] <= u8;
                    u_hat[9] <= u9;
                    u_hat[10] <= u10;
                    u_hat[11] <= u11;
                    u_hat[12] <= u12;
                    u_hat[13] <= u13;
                    u_hat[14] <= u14;
                    u_hat[15] <= u15;
                    busy <= 1'b0;
                    done <= 1'b1;
                    state <= S_IDLE;
                end

                default: begin
                    state <= S_IDLE;
                    busy <= 1'b0;
                    done <= 1'b0;
                end
            endcase
        end
    end

endmodule
