/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/signed_adder.v:3.1-19.10" *)
module signed_adder(a, b, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "rtl/signed_adder.v:6.32-6.33" *)
  input [5:0] a;
  wire [5:0] a;
  (* src = "rtl/signed_adder.v:11.23-11.28" *)
  wire [6:0] a_ext;
  (* src = "rtl/signed_adder.v:7.32-7.33" *)
  input [5:0] b;
  wire [5:0] b;
  (* src = "rtl/signed_adder.v:12.23-12.28" *)
  wire [6:0] b_ext;
  (* src = "rtl/signed_adder.v:8.32-8.33" *)
  output [6:0] y;
  wire [6:0] y;
  assign _00_ = b[0] & a[0];
  assign _01_ = ~(b[1] & a[1]);
  assign _02_ = b[1] ^ a[1];
  assign _03_ = ~(_00_ & _02_);
  assign y[1] = _00_ ^ _02_;
  assign _04_ = ~(_01_ & _03_);
  assign _05_ = ~(b[2] & a[2]);
  assign _06_ = b[2] ^ a[2];
  assign _07_ = ~(_04_ & _06_);
  assign y[2] = _04_ ^ _06_;
  assign _08_ = ~(_05_ & _07_);
  assign _09_ = ~(b[3] & a[3]);
  assign _10_ = b[3] ^ a[3];
  assign _11_ = ~(_08_ & _10_);
  assign y[3] = _08_ ^ _10_;
  assign _12_ = ~(_09_ & _11_);
  assign _13_ = ~(b[4] & a[4]);
  assign _14_ = b[4] ^ a[4];
  assign _15_ = ~(_12_ & _14_);
  assign y[4] = _12_ ^ _14_;
  assign _16_ = _13_ & _15_;
  assign _17_ = ~(b[5] & a[5]);
  assign _18_ = b[5] ^ a[5];
  assign _19_ = ~(_16_ & _18_);
  assign y[5] = ~(_16_ ^ _18_);
  assign y[6] = ~(_17_ & _19_);
  assign y[0] = b[0] ^ a[0];
  assign a_ext = { a[5], a };
  assign b_ext = { b[5], b };
endmodule
