#!/usr/bin/env python3
"""
Generate Project 8.3 RTL:
Resource-shared scheduled SC Decoder N=16.

Input:
    results/schedules/sc_decoder_n16_schedule.csv

Output:
    rtl/sc_decoder_n16_shared.v

Architecture:
    - sequential start/busy/done interface
    - one shared f/g datapath
    - schedule-guided FSM
    - explicit registers for LLRs, partial sums, and decoded bits
"""

from __future__ import annotations

import csv
import math
from pathlib import Path


SCHEDULE_CSV = Path("results/schedules/sc_decoder_n16_schedule.csv")
OUT_RTL = Path("rtl/sc_decoder_n16_shared.v")


def read_schedule(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Missing schedule file: {path}")

    with path.open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise RuntimeError("Schedule CSV is empty.")

    return rows


def state_name(step: int) -> str:
    return f"S_OP_{step:03d}"


def signal_expr(name: str) -> str:
    return name.strip()


def sanitize_expr(expr: str) -> str:
    return expr.strip()


def collect_registers(rows):
    llr_regs = set()
    partial_regs = set()
    u_regs = {f"u{i}" for i in range(16)}

    for r in rows:
        dst = r["destination"].strip()

        if dst.startswith("llr_"):
            llr_regs.add(dst)
        elif dst.startswith("p_"):
            partial_regs.add(dst)

    return sorted(llr_regs), sorted(partial_regs), sorted(u_regs, key=lambda x: int(x[1:]))


def generate_rtl(rows):
    llr_regs, partial_regs, u_regs = collect_registers(rows)

    n_ops = len(rows)
    n_states = n_ops + 3
    state_w = max(1, math.ceil(math.log2(n_states)))

    lines = []

    lines.append("// Project 8.3: Resource-Shared Scheduled SC Decoder N=16")
    lines.append("//")
    lines.append("// Auto-generated by scripts/generate_sc_decoder_n16_shared_rtl.py")
    lines.append("//")
    lines.append("// Conventions:")
    lines.append("//   frozen_mask[i] = 1 -> frozen bit, force u_i = 0")
    lines.append("//   frozen_mask[i] = 0 -> information bit")
    lines.append("//   hard decision: LLR < 0 -> 1, otherwise 0")
    lines.append("//   g(a,b,u): b + a if u=0, b - a if u=1")
    lines.append("//   u_hat[0] = u0, LSB-first ordering")
    lines.append("")
    lines.append("`timescale 1ns/1ps")
    lines.append("")
    lines.append("module sc_decoder_n16_shared #(")
    lines.append("    parameter W_IN  = 6,")
    lines.append("    parameter W_INT = 10")
    lines.append(")(")
    lines.append("    input  wire clk,")
    lines.append("    input  wire rst_n,")
    lines.append("    input  wire start,")
    lines.append("")
    for i in range(16):
        comma = "," if i < 15 else ","
        lines.append(f"    input  wire signed [W_IN-1:0] llr{i}{comma}")
    lines.append("")
    lines.append("    input  wire [15:0] frozen_mask,")
    lines.append("")
    lines.append("    output reg  [15:0] u_hat,")
    lines.append("    output reg         busy,")
    lines.append("    output reg         done")
    lines.append(");")
    lines.append("")
    lines.append(f"    localparam integer STATE_W = {state_w};")
    lines.append("")
    lines.append("    localparam [STATE_W-1:0] S_IDLE = 0;")
    lines.append("    localparam [STATE_W-1:0] S_LOAD = 1;")
    for idx in range(n_ops):
        lines.append(f"    localparam [STATE_W-1:0] {state_name(idx)} = {idx + 2};")
    lines.append(f"    localparam [STATE_W-1:0] S_DONE = {n_ops + 2};")
    lines.append("")
    lines.append("    reg [STATE_W-1:0] state;")
    lines.append("    reg [15:0] frozen_mask_reg;")
    lines.append("")

    for i in range(16):
        lines.append(f"    reg signed [W_INT-1:0] L{i};")
    lines.append("")

    for r in llr_regs:
        lines.append(f"    reg signed [W_INT-1:0] {r};")
    lines.append("")

    for r in partial_regs:
        lines.append(f"    reg {r};")
    lines.append("")

    for r in u_regs:
        lines.append(f"    reg {r};")
    lines.append("")

    lines.append("    reg signed [W_INT-1:0] fu_a;")
    lines.append("    reg signed [W_INT-1:0] fu_b;")
    lines.append("    reg                    fu_is_g;")
    lines.append("    reg                    fu_g_bit;")
    lines.append("    wire signed [W_INT-1:0] fu_y;")
    lines.append("")
    lines.append("    function signed [W_INT-1:0] f_func;")
    lines.append("        input signed [W_INT-1:0] a;")
    lines.append("        input signed [W_INT-1:0] b;")
    lines.append("        reg signed [W_INT-1:0] abs_a;")
    lines.append("        reg signed [W_INT-1:0] abs_b;")
    lines.append("        reg signed [W_INT-1:0] mag;")
    lines.append("        reg negative;")
    lines.append("        begin")
    lines.append("            abs_a = a[W_INT-1] ? -a : a;")
    lines.append("            abs_b = b[W_INT-1] ? -b : b;")
    lines.append("            mag = (abs_a < abs_b) ? abs_a : abs_b;")
    lines.append("            negative = a[W_INT-1] ^ b[W_INT-1];")
    lines.append("            f_func = negative ? -mag : mag;")
    lines.append("        end")
    lines.append("    endfunction")
    lines.append("")
    lines.append("    function signed [W_INT-1:0] g_func;")
    lines.append("        input signed [W_INT-1:0] a;")
    lines.append("        input signed [W_INT-1:0] b;")
    lines.append("        input u;")
    lines.append("        begin")
    lines.append("            g_func = (u == 1'b0) ? (b + a) : (b - a);")
    lines.append("        end")
    lines.append("    endfunction")
    lines.append("")
    lines.append("    function hard_decision;")
    lines.append("        input signed [W_INT-1:0] llr;")
    lines.append("        begin")
    lines.append("            hard_decision = (llr < 0) ? 1'b1 : 1'b0;")
    lines.append("        end")
    lines.append("    endfunction")
    lines.append("")
    lines.append("    assign fu_y = fu_is_g ? g_func(fu_a, fu_b, fu_g_bit)")
    lines.append("                           : f_func(fu_a, fu_b);")
    lines.append("")

    lines.append("    always @* begin")
    lines.append("        fu_a = {W_INT{1'b0}};")
    lines.append("        fu_b = {W_INT{1'b0}};")
    lines.append("        fu_is_g = 1'b0;")
    lines.append("        fu_g_bit = 1'b0;")
    lines.append("")
    lines.append("        case (state)")
    for idx, r in enumerate(rows):
        op = r["op_type"].strip()
        if op in ("F", "G"):
            a = signal_expr(r["operand_a"])
            b = signal_expr(r["operand_b"])
            gbit = signal_expr(r["g_bit"])
            is_g = "1'b1" if op == "G" else "1'b0"
            gbit_expr = gbit if op == "G" else "1'b0"
            lines.append(f"            {state_name(idx)}: begin")
            lines.append(f"                fu_a = {a};")
            lines.append(f"                fu_b = {b};")
            lines.append(f"                fu_is_g = {is_g};")
            lines.append(f"                fu_g_bit = {gbit_expr};")
            lines.append("            end")
    lines.append("            default: begin")
    lines.append("                fu_a = {W_INT{1'b0}};")
    lines.append("                fu_b = {W_INT{1'b0}};")
    lines.append("                fu_is_g = 1'b0;")
    lines.append("                fu_g_bit = 1'b0;")
    lines.append("            end")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")

    lines.append("    always @(posedge clk or negedge rst_n) begin")
    lines.append("        if (!rst_n) begin")
    lines.append("            state <= S_IDLE;")
    lines.append("            frozen_mask_reg <= 16'd0;")
    lines.append("            u_hat <= 16'd0;")
    lines.append("            busy <= 1'b0;")
    lines.append("            done <= 1'b0;")
    for i in range(16):
        lines.append(f"            L{i} <= {{W_INT{{1'b0}}}};")
    for r in llr_regs:
        lines.append(f"            {r} <= {{W_INT{{1'b0}}}};")
    for r in partial_regs:
        lines.append(f"            {r} <= 1'b0;")
    for r in u_regs:
        lines.append(f"            {r} <= 1'b0;")
    lines.append("        end else begin")
    lines.append("            done <= 1'b0;")
    lines.append("")
    lines.append("            case (state)")
    lines.append("                S_IDLE: begin")
    lines.append("                    busy <= 1'b0;")
    lines.append("                    if (start) begin")
    lines.append("                        busy <= 1'b1;")
    lines.append("                        state <= S_LOAD;")
    lines.append("                    end")
    lines.append("                end")
    lines.append("")
    lines.append("                S_LOAD: begin")
    lines.append("                    busy <= 1'b1;")
    lines.append("                    frozen_mask_reg <= frozen_mask;")
    for i in range(16):
        lines.append(f"                    L{i} <= {{{{(W_INT-W_IN){{llr{i}[W_IN-1]}}}}, llr{i}}};")
    lines.append(f"                    state <= {state_name(0)};")
    lines.append("                end")
    lines.append("")

    for idx, r in enumerate(rows):
        op = r["op_type"].strip()
        dst = r["destination"].strip()
        next_state = state_name(idx + 1) if idx + 1 < n_ops else "S_DONE"

        lines.append(f"                {state_name(idx)}: begin")
        if op in ("F", "G"):
            lines.append(f"                    {dst} <= fu_y;")
        elif op == "DECISION":
            bit_index = int(dst[1:])
            a = signal_expr(r["operand_a"])
            lines.append(f"                    {dst} <= frozen_mask_reg[{bit_index}] ? 1'b0 : hard_decision({a});")
        elif op == "PARTIAL":
            expr = r["expression"].strip()
            rhs = expr.split("=", 1)[1].strip() if "=" in expr else r["operand_a"].strip()
            rhs = sanitize_expr(rhs)
            lines.append(f"                    {dst} <= {rhs};")
        else:
            raise RuntimeError(f"Unsupported op_type: {op}")
        lines.append(f"                    state <= {next_state};")
        lines.append("                end")
        lines.append("")

    lines.append("                S_DONE: begin")
    for i in range(16):
        lines.append(f"                    u_hat[{i}] <= u{i};")
    lines.append("                    busy <= 1'b0;")
    lines.append("                    done <= 1'b1;")
    lines.append("                    state <= S_IDLE;")
    lines.append("                end")
    lines.append("")
    lines.append("                default: begin")
    lines.append("                    state <= S_IDLE;")
    lines.append("                    busy <= 1'b0;")
    lines.append("                    done <= 1'b0;")
    lines.append("                end")
    lines.append("            endcase")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")
    lines.append("")

    return "\n".join(lines)


def main():
    rows = read_schedule(SCHEDULE_CSV)
    rtl = generate_rtl(rows)

    OUT_RTL.parent.mkdir(parents=True, exist_ok=True)
    OUT_RTL.write_text(rtl, encoding="utf-8")

    print(f"[OK] Read schedule: {SCHEDULE_CSV}")
    print(f"[OK] Number of schedule rows: {len(rows)}")
    print(f"[OK] Wrote RTL: {OUT_RTL}")


if __name__ == "__main__":
    main()